name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  QA:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: ./api
        run: sudo npm install

      - name: Run audit
        working-directory: ./api
        run: sudo npm audit

      - name: Run lint
        working-directory: ./api
        run: sudo npm run lint:ci
